### ISSUE TITLE
synapse crashes when trying to send a message

### ISSUE THREAD

**Issue by hanseartic** [matrix-org/synapse-spamcheck-badlist#10]
**Describe the bug**
When trying to send a message (tried with element web and FluffyChat) to a federated chat-room the message is not sent (marked as failed, option to try to send again is shown).

**To Reproduce**
1. Install `synapse-spamcheck-badlist` via pip in synapses python environment
2. Configure synapse to use the module in `spam_checker` section
3. Create two tables in synapses database matching the table-names configured in step 2
4. Restart synapse
5. Try to send a message in a group-chat

**Expected behavior**
The message should be sent and visible on all clients connected to the room.

**Server:**
- Homeserver: synapse
- Version: 1.26.0

**Desktop:**
 - OS: OSX
 - Browser: Firefox
 - Version: 78.7
 - Client: element 1.7.20

**Smartphone:**
 - Device: Nokia 8.1
 - OS: Android 9
 - Browser: FluffyChat
 - Version: 0.26.1

**Additional context**
redacted snipped from synapses `homeserver.log`:
```
AttributeError: Not an Aho-Corasick automaton yet: call add_word to add some keys and call make_automaton to convert the trie to an automaton.
0000-00-00 00:00:00,000 - synapse.http.server - 83 - ERROR - PUT-493 - Failed handle request via 'RoomSendEventRestServlet': <XForwardedForRequest at 0x7fa75344da20 method='PUT' uri='/_matrix/client/r0/rooms/!DzntlyFqDwYZSqoYBV%3Amaunium.net/send/m.room.message/FluffyChat%20android-4-1613025057873' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/***/.local/lib/python3.6/site-packages/synapse/rest/client/v1/room.py", line 241, in on_POST
    requester, event_dict, txn_id=txn_id
  File "/home/***/.local/lib/python3.6/site-packages/synapse/handlers/message.py", line 747, in create_and_send_nonmember_event
    spam_error = await self.spam_checker.check_event_for_spam(event)
  File "/home/***/.local/lib/python3.6/site-packages/synapse/events/spamcheck.py", line 60, in check_event_for_spam
    if await maybe_awaitable(spam_checker.check_event_for_spam(event)):
  File "/home/***/src/synapse-spamcheck-badlist/synapse_spamcheck_badlist/bad_list_filter.py", line 145, in check_event_for_spam
    for _ in automaton.iter(text):
AttributeError: Not an Aho-Corasick automaton yet: call add_word to add some keys and call make_automaton to convert the trie to an automaton.
0000-00-00 00:00:00, - synapse.federation.federation_server - 362 - ERROR - PUT-695-$XXXXXX-laAxSkdZ4Y4 - Failed to handle PDU $XXXXXX-laAxSkdZ4Y4
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/***/.local/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 351, in process_pdus_for_room
    await self._handle_received_pdu(origin, pdu)
  File "/home/***/.local/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 736, in _handle_received_pdu
    pdu = await self._check_sigs_and_hash(room_version, pdu)
AttributeError: Not an Aho-Corasick automaton yet: call add_word to add some keys and call make_automaton to convert the trie to an automaton.
```

**Comment by erikjohnston** [comment]
Hmm, I thought this was fixed by https://github.com/matrix-org/synapse-spamcheck-badlist/pull/9. What version are you using?

**Comment by hanseartic** [comment]
Hi,
thank you for the swift response. I am using `0.2.0`:
```
$ pip3.6 list --format=columns|grep synapse-spamcheck
synapse-spamcheck-badlist   0.2.0
```
Apparently the latest version is not published:
```
$ pip3.6 install --user -U "git+https://github.com/matrix-org/synapse-spamcheck-badlist#egg=synapse-spamcheck-badlist"
Collecting synapse-spamcheck-badlist from git+https://github.com/matrix-org/synapse-spamcheck-badlist#egg=synapse-spamcheck-badlist
  Cloning https://github.com/matrix-org/synapse-spamcheck-badlist to /tmp/pip-build-6vam7cf_/synapse-spamcheck-badlist
Requirement already up-to-date: pyahocorasick in ./.local/lib/python3.6/site-packages (from synapse-spamcheck-badlist)
Requirement already up-to-date: prometheus-client in ./.local/lib/python3.6/site-packages (from synapse-spamcheck-badlist)
Requirement already up-to-date: twisted in ./.local/lib/python3.6/site-packages (from synapse-spamcheck-badlist)
Requirement already up-to-date: zope.interface>=4.4.2 in ./.local/lib/python3.6/site-packages (from twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: constantly>=15.1 in ./.local/lib/python3.6/site-packages (from twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: incremental>=16.10.1 in ./.local/lib/python3.6/site-packages (from twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: attrs>=19.2.0 in ./.local/lib/python3.6/site-packages (from twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: PyHamcrest!=1.10.0,>=1.9.0 in ./.local/lib/python3.6/site-packages (from twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: hyperlink>=17.1.1 in ./.local/lib/python3.6/site-packages (from twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: Automat>=0.3.0 in ./.local/lib/python3.6/site-packages (from twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: setuptools in ./.local/lib/python3.6/site-packages (from zope.interface>=4.4.2->twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: idna>=2.5 in ./.local/lib/python3.6/site-packages (from hyperlink>=17.1.1->twisted->synapse-spamcheck-badlist)
Requirement already up-to-date: six in ./.local/lib/python3.6/site-packages (from Automat>=0.3.0->twisted->synapse-spamcheck-badlist)
Installing collected packages: synapse-spamcheck-badlist
  Running setup.py install for synapse-spamcheck-badlist ... done
Successfully installed synapse-spamcheck-badlist-0.2.0
```

**Comment by hanseartic** [comment]
Or, you just did not bump the version: https://github.com/matrix-org/synapse-spamcheck-badlist/blob/66c31fd7b573e78d6562627ac8f94ffc45ae49fe/setup.py#L5

**Comment by erikjohnston** [comment]
I... bumped the version and tagged on the wrong branch :facepalm: 

Should be fixed now :crossed_fingers:
