### ISSUE TITLE
Failed to handle PDU

### ISSUE THREAD

**Issue by MomentQYC** [matrix-org/synapse-spamcheck-badlist#28]
Synapse 1.73.0
Python3.8
Ubuntu 20.04

When I used it, I found a large number of errors, such as

```
2022-12-13 00:00:14,690 - synapse.federation.federation_server - 504 - ERROR - PUT-235833-!ttKPgmaucSQTHmGurC: example.com -$VSsQ9L4ygzCuIqA1Lc_LGTvPuQsPXKBGSZQBteBTeoY - Failed to handle PDU $VSsQ9L4ygzCuIqA1Lc_LGTvPuQsPXKBGSZQBteBTeoY
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/federation/federation_server.py", line 497, in process_pdu
    await self._handle_received_pdu(origin, pdu)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/federation/federation_server.py", line 1112, in _handle_received_pdu
    pdu = await self._check_sigs_and_hash(room_version, pdu)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/logging/opentracing.py", line 889, in _wrapper
    return await func(*args, **kwargs)  # type: ignore[misc]
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/federation/federation_base.py", line 140, in _check_sigs_and_hash
    spam_check = await self.spam_checker.check_event_for_spam(pdu)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/logging/opentracing.py", line 889, in _wrapper
    return await func(*args, **kwargs)  # type: ignore[misc]
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/events/spamcheck.py", line 408, in check_event_for_spam
    res = await delay_cancellation(callback(event))
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = 
context.run
(gen.send, result)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse_spamcheck_badlist/bad_list_filter.py", line 167, in check_event_for_spam
    for _ in automaton.iter(text):
AttributeError: Not an Aho-Corasick automaton yet: call add_word to add some keys and call make_automaton to convert the trie to an automaton.
```
I found that the federation function was severely affected.

**Comment by squahtx** [comment]
That looks like the `links_table` has been improperly configured, or is empty.

**Comment by MomentQYC** [comment]
> That looks like the `links_table` has been improperly configured, or is empty. How many rows were in the `links_table` at the time?

I see, it is indeed because the database related part is empty inside.
